-- ===========================================================================
-- Real Strategy
-- Author: Infixo
-- 2018-12-14: Created
-- ===========================================================================

-- just to make versioning easier
INSERT INTO GlobalParameters (Name, Value) VALUES ('RST_VERSION_MAJOR', '0');
INSERT INTO GlobalParameters (Name, Value) VALUES ('RST_VERSION_MINOR', '1');

-- Parameters
INSERT INTO GlobalParameters (Name, Value) VALUES
('RST_WEIGHT_POLICY', 3), -- how much each slotted policy weights
('RST_WEIGHT_WONDER', 3), -- how much each wonder weights
('RST_WEIGHT_GOVERNMENT', 5), -- how much each government weights
('RST_WEIGHT_MINOR', 3), -- how much each suzerained city state weights
('RST_STRATEGY_NUM_TURNS_MUST_BE_ACTIVE', 5), -- how many turns a strategy must be active before checking for new priorities, def. 10
('RST_STRATEGY_MINIMUM_PRIORITY', 100), -- minimum priority to activate a strategy
('RST_STRATEGY_CURRENT_PRIORITY', 50), -- how much current strategy adds to the priority
('RST_STRATEGY_RANDOM_PRIORITY', 30), -- random part of the priority, def. 50
('RST_STRATEGY_BETTER_THAN_US_NERF', 33), -- each player better than us decreases our priority by this percent
('RST_STRATEGY_COMPARE_OTHERS_NUM_TURNS', 30), -- def. 60, generic parameter for all strategies, we will start comparing with other known civs after this many turns
('RST_CONQUEST_NOBODY_MET_NUM_TURNS', 20), -- will check if anybody met after this many turns, def. 20
('RST_CONQUEST_NOBODY_MET_PRIORITY', -100), -- if nobody met, then decrease the priority, def. -100
('RST_CONQUEST_CAPTURED_CAPITAL_PRIORITY', 50), -- increase conquest priority for each captured capital if we have more than 1, def. 125 + added in VP, seems quite a lot?
--('RST_CONQUEST_POWER_FIRST_TURN', 20), -- check for military strength only after this many turns, def. 60
('RST_CONQUEST_POWER_RATIO_MULTIPLIER', 100), -- how does our military strength compare to others, -100 = we are at 0, 0 = we are average, +100 = we are 2x as average, +200 = we are 3x as average, etc.
('RST_CONQUEST_AT_WAR_PRIORITY', 10), -- conquest priority for each ongoing war with a major civ, def. 10
('RST_CONQUEST_SOMEONE_CLOSE_TO_VICTORY', 20), -- add this for each player close to victory when we are NOT, def. 25 (desperate!), multiplied by ERA - seems a lot!!!
('RST_CONQUEST_BOTH_CLOSE_TO_VICTORY', 5), -- add this for each player close to victory when we are too, def. 5, multiplied by ERA
('RST_CONQUEST_LESS_CITIES_WEIGHT', 15), -- added for each city we have less than all known civs on average, because conquest is a wide play, check together with power
('RST_CONQUEST_NUKE_THREAT', -50), -- others have WMDs, but we don't, counted only once?
('RST_SCIENCE_ERA_BIAS', 150), -- [x100] leader's individual bias is multiplied by Era and this factor, def. 250, for Atomic=7, low=2 mid=5 high=8 => 21 / 53 / 86
('RST_SCIENCE_YIELD_WEIGHT', 15), -- [x100] how much each beaker weights
('RST_SCIENCE_TECH_WEIGHT', 20), -- each tech we are ahead of average -- with techs it is difficult to be very ahead, and techs are limited, so each one is important
('RST_SCIENCE_PROJECT_WEIGHT', 75), -- each completed space race project
('RST_SCIENCE_HAS_SPACEPORT', 40); -- adds if player has a spaceport

/*
INSERT INTO Types (Type, Kind) VALUES
('STRATEGY_TEST_TURN_3', 'KIND_VICTORY_STRATEGY'),
('STRATEGY_TEST_TURN_5', 'KIND_VICTORY_STRATEGY'),
('STRATEGY_TEST_TURN_7', 'KIND_VICTORY_STRATEGY');

INSERT INTO Strategies (StrategyType, VictoryType, NumConditionsNeeded) VALUES
('STRATEGY_TEST_TURN_3', NULL, 1),
('STRATEGY_TEST_TURN_5', NULL, 1),
('STRATEGY_TEST_TURN_7', NULL, 1);
 */

--INSERT INTO StrategyConditions (StrategyType, ConditionFunction, StringValue, ThresholdValue) VALUES
--('STRATTEST_TURN_3','Call Lua Function','CheckTurnNumber',3),
--('STRATTEST_TURN_5','Call Lua Function','CheckTurnNumber',5),
--('STRATTEST_TURN_7','Call Lua Function','CheckTurnNumber',7);


--Good Culture City
--Good Faith City
--Good Tech City
/*
INSERT INTO StrategyConditions (StrategyType, ConditionFunction, ThresholdValue) VALUES
('STRATTEST_Has_Tech_Lead_15', 'Has Tech Lead', 15),
('STRATTEST_Has_Tech_Lead_25', 'Has Tech Lead', 25),
('STRATTEST_Has_Tech_Lead_50', 'Has Tech Lead', 50),
('STRATTEST_Leads_Military_15', 'Leads Military', 15),
('STRATTEST_Leads_Military_25', 'Leads Military', 25),
('STRATTEST_Leads_Military_50', 'Leads Military', 50),
('STRATTEST_Leads_Score_15', 'Leads Score', 15), -- 1/8
('STRATTEST_Leads_Score_25', 'Leads Score', 25), -- 2/8
('STRATTEST_Leads_Score_50', 'Leads Score', 50), -- 4/8
--('STRATTEST_Next_Lower_Score_20', 'Next Lower Score', 20),
--('STRATTEST_Next_Lower_Score_40', 'Next Lower Score', 40),
--('STRATTEST_Next_Lower_Score_60', 'Next Lower Score', 60);
('STRATTEST_Is_Classical_0', 'Is Classical', 0),
('STRATTEST_Is_Classical_1', 'Is Classical', 1),
('STRATTEST_Is_Medieval_0', 'Is Medieval', 0),
('STRATTEST_Is_Medieval_1', 'Is Medieval', 1);


INSERT INTO Types (Type, Kind)
SELECT StrategyType, 'KIND_VICTORY_STRATEGY'
FROM StrategyConditions
WHERE StrategyType LIKE 'STRATTEST%';

INSERT INTO Strategies (StrategyType, NumConditionsNeeded)
SELECT StrategyType, 1
FROM StrategyConditions
WHERE StrategyType LIKE 'STRATTEST%';
*/

CREATE TABLE RSTFlavors (
	ObjectType TEXT NOT NULL,
	Type TEXT NOT NULL CHECK (Type IN ('Parameter', 'STRATEGY', 'LEADER', 'POLICY', 'GOVERNMENT', 'Wonder', 'BELIEF', 'CityState')),
	Subtype TEXT,
	Strategy TEXT NOT NULL CHECK (Strategy IN ('CONQUEST', 'SCIENCE', 'CULTURE', 'RELIGION', 'DIPLO', 'DEFENCE', 'NAVAL', 'TRADE')),
	Value INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (ObjectType, Strategy)
);

INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
('BasePriority', 'Parameter', 'STRATEGY', 'SCIENCE', 20),	('BasePriority', 'Parameter', 'STRATEGY', 'CULTURE', 20),	('BasePriority', 'Parameter', 'STRATEGY', 'RELIGION', 20),	('BasePriority', 'Parameter', 'STRATEGY', 'CONQUEST', 20),
('SCIENCE', 'Parameter', 'STRATEGY', 'SCIENCE', 2),	('SCIENCE', 'Parameter', 'STRATEGY', 'CULTURE', -2),	('SCIENCE', 'Parameter', 'STRATEGY', 'RELIGION', -2),	('SCIENCE', 'Parameter', 'STRATEGY', 'CONQUEST', 1),
('CULTURE', 'Parameter', 'STRATEGY', 'SCIENCE', -2),	('CULTURE', 'Parameter', 'STRATEGY', 'CULTURE', 2),	('CULTURE', 'Parameter', 'STRATEGY', 'RELIGION', -1),	('CULTURE', 'Parameter', 'STRATEGY', 'CONQUEST', -2),
('RELIGION', 'Parameter', 'STRATEGY', 'SCIENCE', -2),	('RELIGION', 'Parameter', 'STRATEGY', 'CULTURE', -1),	('RELIGION', 'Parameter', 'STRATEGY', 'RELIGION', 2),	
('CONQUEST', 'Parameter', 'STRATEGY', 'SCIENCE', 1),	('CONQUEST', 'Parameter', 'STRATEGY', 'CULTURE', -1),	('CONQUEST', 'Parameter', 'STRATEGY', 'RELIGION', -1),	('CONQUEST', 'Parameter', 'STRATEGY', 'CONQUEST', 3),
('DIPLO', 'Parameter', 'STRATEGY', 'CULTURE', 1),		('DIPLO', 'Parameter', 'STRATEGY', 'CONQUEST', -1);

-- LEADERS
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
('LEADER_ALEXANDER', 'LEADER', '', 'SCIENCE', 5),	('LEADER_ALEXANDER', 'LEADER', '', 'CULTURE', 4),	('LEADER_ALEXANDER', 'LEADER', '', 'RELIGION', 3),	('LEADER_ALEXANDER', 'LEADER', '', 'CONQUEST', 8),
('LEADER_AMANITORE', 'LEADER', '', 'SCIENCE', 2),	('LEADER_AMANITORE', 'LEADER', '', 'CULTURE', 3),	('LEADER_AMANITORE', 'LEADER', '', 'RELIGION', 6),	('LEADER_AMANITORE', 'LEADER', '', 'CONQUEST', 5),
('LEADER_BARBAROSSA', 'LEADER', '', 'SCIENCE', 7),	('LEADER_BARBAROSSA', 'LEADER', '', 'CULTURE', 4),	('LEADER_BARBAROSSA', 'LEADER', '', 'RELIGION', 4),	('LEADER_BARBAROSSA', 'LEADER', '', 'CONQUEST', 6),
('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'SCIENCE', 6),	('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'CULTURE', 8),	('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'RELIGION', 4),	('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'CONQUEST', 4),
('LEADER_CHANDRAGUPTA', 'LEADER', '', 'SCIENCE', 4),	('LEADER_CHANDRAGUPTA', 'LEADER', '', 'CULTURE', 4),	('LEADER_CHANDRAGUPTA', 'LEADER', '', 'RELIGION', 5),	('LEADER_CHANDRAGUPTA', 'LEADER', '', 'CONQUEST', 6),
('LEADER_CLEOPATRA', 'LEADER', '', 'SCIENCE', 5),	('LEADER_CLEOPATRA', 'LEADER', '', 'CULTURE', 6),	('LEADER_CLEOPATRA', 'LEADER', '', 'RELIGION', 5),	('LEADER_CLEOPATRA', 'LEADER', '', 'CONQUEST', 5),
('LEADER_CYRUS', 'LEADER', '', 'SCIENCE', 5),	('LEADER_CYRUS', 'LEADER', '', 'CULTURE', 4),	('LEADER_CYRUS', 'LEADER', '', 'RELIGION', 4),	('LEADER_CYRUS', 'LEADER', '', 'CONQUEST', 8),
('LEADER_GANDHI', 'LEADER', '', 'SCIENCE', 5),	('LEADER_GANDHI', 'LEADER', '', 'CULTURE', 7),	('LEADER_GANDHI', 'LEADER', '', 'RELIGION', 8),	('LEADER_GANDHI', 'LEADER', '', 'CONQUEST', 2),
('LEADER_GENGHIS_KHAN', 'LEADER', '', 'SCIENCE', 4),	('LEADER_GENGHIS_KHAN', 'LEADER', '', 'CULTURE', 2),	('LEADER_GENGHIS_KHAN', 'LEADER', '', 'RELIGION', 2),	('LEADER_GENGHIS_KHAN', 'LEADER', '', 'CONQUEST', 8),
('LEADER_GILGAMESH', 'LEADER', '', 'SCIENCE', 8),	('LEADER_GILGAMESH', 'LEADER', '', 'CULTURE', 4),	('LEADER_GILGAMESH', 'LEADER', '', 'RELIGION', 2),	('LEADER_GILGAMESH', 'LEADER', '', 'CONQUEST', 5),
('LEADER_GITARJA', 'LEADER', '', 'SCIENCE', 4),	('LEADER_GITARJA', 'LEADER', '', 'CULTURE', 5),	('LEADER_GITARJA', 'LEADER', '', 'RELIGION', 7),	('LEADER_GITARJA', 'LEADER', '', 'CONQUEST', 3),
('LEADER_GORGO', 'LEADER', '', 'SCIENCE', 2),	('LEADER_GORGO', 'LEADER', '', 'CULTURE', 5),	('LEADER_GORGO', 'LEADER', '', 'RELIGION', 3),	('LEADER_GORGO', 'LEADER', '', 'CONQUEST', 7),
('LEADER_HARDRADA', 'LEADER', '', 'SCIENCE', 5),	('LEADER_HARDRADA', 'LEADER', '', 'CULTURE', 1),	('LEADER_HARDRADA', 'LEADER', '', 'RELIGION', 5),	('LEADER_HARDRADA', 'LEADER', '', 'CONQUEST', 7),
('LEADER_HOJO', 'LEADER', '', 'SCIENCE', 5),	('LEADER_HOJO', 'LEADER', '', 'CULTURE', 4),	('LEADER_HOJO', 'LEADER', '', 'RELIGION', 2),	('LEADER_HOJO', 'LEADER', '', 'CONQUEST', 7),
('LEADER_JADWIGA', 'LEADER', '', 'SCIENCE', 4),	('LEADER_JADWIGA', 'LEADER', '', 'CULTURE', 6),	('LEADER_JADWIGA', 'LEADER', '', 'RELIGION', 7),	('LEADER_JADWIGA', 'LEADER', '', 'CONQUEST', 4),
('LEADER_JAYAVARMAN', 'LEADER', '', 'SCIENCE', 4),	('LEADER_JAYAVARMAN', 'LEADER', '', 'CULTURE', 5),	('LEADER_JAYAVARMAN', 'LEADER', '', 'RELIGION', 8),	('LEADER_JAYAVARMAN', 'LEADER', '', 'CONQUEST', 3),
('LEADER_JOHN_CURTIN', 'LEADER', '', 'SCIENCE', 6),	('LEADER_JOHN_CURTIN', 'LEADER', '', 'CULTURE', 6),	('LEADER_JOHN_CURTIN', 'LEADER', '', 'RELIGION', 4),	('LEADER_JOHN_CURTIN', 'LEADER', '', 'CONQUEST', 4),
('LEADER_LAUTARO', 'LEADER', '', 'SCIENCE', 2),	('LEADER_LAUTARO', 'LEADER', '', 'CULTURE', 7),	('LEADER_LAUTARO', 'LEADER', '', 'RELIGION', 3),	('LEADER_LAUTARO', 'LEADER', '', 'CONQUEST', 7),
('LEADER_MONTEZUMA', 'LEADER', '', 'SCIENCE', 3),	('LEADER_MONTEZUMA', 'LEADER', '', 'CULTURE', 2),	('LEADER_MONTEZUMA', 'LEADER', '', 'RELIGION', 2),	('LEADER_MONTEZUMA', 'LEADER', '', 'CONQUEST', 9),
('LEADER_MVEMBA', 'LEADER', '', 'SCIENCE', 6),	('LEADER_MVEMBA', 'LEADER', '', 'CULTURE', 8),	('LEADER_MVEMBA', 'LEADER', '', 'RELIGION', 1),	('LEADER_MVEMBA', 'LEADER', '', 'CONQUEST', 2),
('LEADER_PEDRO', 'LEADER', '', 'SCIENCE', 6),	('LEADER_PEDRO', 'LEADER', '', 'CULTURE', 8),	('LEADER_PEDRO', 'LEADER', '', 'RELIGION', 3),	('LEADER_PEDRO', 'LEADER', '', 'CONQUEST', 3),
('LEADER_PERICLES', 'LEADER', '', 'SCIENCE', 5),	('LEADER_PERICLES', 'LEADER', '', 'CULTURE', 8),	('LEADER_PERICLES', 'LEADER', '', 'RELIGION', 3),	('LEADER_PERICLES', 'LEADER', '', 'CONQUEST', 3),
('LEADER_PETER_GREAT', 'LEADER', '', 'SCIENCE', 5),	('LEADER_PETER_GREAT', 'LEADER', '', 'CULTURE', 5),	('LEADER_PETER_GREAT', 'LEADER', '', 'RELIGION', 6),	('LEADER_PETER_GREAT', 'LEADER', '', 'CONQUEST', 4),
('LEADER_PHILIP_II', 'LEADER', '', 'SCIENCE', 4),	('LEADER_PHILIP_II', 'LEADER', '', 'CULTURE', 3),	('LEADER_PHILIP_II', 'LEADER', '', 'RELIGION', 7),	('LEADER_PHILIP_II', 'LEADER', '', 'CONQUEST', 5),
('LEADER_POUNDMAKER', 'LEADER', '', 'SCIENCE', 6),	('LEADER_POUNDMAKER', 'LEADER', '', 'CULTURE', 5),	('LEADER_POUNDMAKER', 'LEADER', '', 'RELIGION', 5),	('LEADER_POUNDMAKER', 'LEADER', '', 'CONQUEST', 4),
('LEADER_QIN', 'LEADER', '', 'SCIENCE', 6),	('LEADER_QIN', 'LEADER', '', 'CULTURE', 7),	('LEADER_QIN', 'LEADER', '', 'RELIGION', 5),	('LEADER_QIN', 'LEADER', '', 'CONQUEST', 5),
('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'SCIENCE', 7),	('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'CULTURE', 4),	('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'RELIGION', 2),	('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'CONQUEST', 4),
('LEADER_SALADIN', 'LEADER', '', 'SCIENCE', 7),	('LEADER_SALADIN', 'LEADER', '', 'CULTURE', 4),	('LEADER_SALADIN', 'LEADER', '', 'RELIGION', 7),	('LEADER_SALADIN', 'LEADER', '', 'CONQUEST', 4),
('LEADER_SEONDEOK', 'LEADER', '', 'SCIENCE', 9),	('LEADER_SEONDEOK', 'LEADER', '', 'CULTURE', 5),	('LEADER_SEONDEOK', 'LEADER', '', 'RELIGION', 1),	('LEADER_SEONDEOK', 'LEADER', '', 'CONQUEST', 5),
('LEADER_SHAKA', 'LEADER', '', 'SCIENCE', 3),	('LEADER_SHAKA', 'LEADER', '', 'CULTURE', 2),	('LEADER_SHAKA', 'LEADER', '', 'RELIGION', 2),	('LEADER_SHAKA', 'LEADER', '', 'CONQUEST', 9),
('LEADER_TAMAR', 'LEADER', '', 'SCIENCE', 3),	('LEADER_TAMAR', 'LEADER', '', 'CULTURE', 4),	('LEADER_TAMAR', 'LEADER', '', 'RELIGION', 7),	('LEADER_TAMAR', 'LEADER', '', 'CONQUEST', 6),
('LEADER_TOMYRIS', 'LEADER', '', 'SCIENCE', 2),	('LEADER_TOMYRIS', 'LEADER', '', 'CULTURE', 3),	('LEADER_TOMYRIS', 'LEADER', '', 'RELIGION', 4),	('LEADER_TOMYRIS', 'LEADER', '', 'CONQUEST', 8),
('LEADER_TRAJAN', 'LEADER', '', 'SCIENCE', 4),	('LEADER_TRAJAN', 'LEADER', '', 'CULTURE', 2),	('LEADER_TRAJAN', 'LEADER', '', 'RELIGION', 2),	('LEADER_TRAJAN', 'LEADER', '', 'CONQUEST', 8),
('LEADER_T_ROOSEVELT', 'LEADER', '', 'SCIENCE', 5),	('LEADER_T_ROOSEVELT', 'LEADER', '', 'CULTURE', 7),	('LEADER_T_ROOSEVELT', 'LEADER', '', 'RELIGION', 3),	('LEADER_T_ROOSEVELT', 'LEADER', '', 'CONQUEST', 4),
('LEADER_VICTORIA', 'LEADER', '', 'SCIENCE', 5),	('LEADER_VICTORIA', 'LEADER', '', 'CULTURE', 7),	('LEADER_VICTORIA', 'LEADER', '', 'RELIGION', 2),	('LEADER_VICTORIA', 'LEADER', '', 'CONQUEST', 7),
('LEADER_WILHELMINA', 'LEADER', '', 'SCIENCE', 5),	('LEADER_WILHELMINA', 'LEADER', '', 'CULTURE', 6),	('LEADER_WILHELMINA', 'LEADER', '', 'RELIGION', 2),	('LEADER_WILHELMINA', 'LEADER', '', 'CONQUEST', 5);

-- GOVERNMENTS
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'SCIENCE', 2),	('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'CULTURE', 2),	('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'RELIGION', 2),	('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'CONQUEST', 2),
('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'SCIENCE', 2),	('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'CULTURE', 4),	('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'RELIGION', 2),	('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'CONQUEST', 4),
('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'SCIENCE', 2),	('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'CULTURE', 2),	('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'RELIGION', 2),	('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'CONQUEST', 6),
('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'SCIENCE', 3),	('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'CULTURE', 3),	('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'RELIGION', 2),	('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'CONQUEST', 1),
('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'SCIENCE', 2),	('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'CULTURE', 2),	('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'RELIGION', 2),	('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'CONQUEST', 4),
('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'SCIENCE', 2),	('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'CULTURE', 2),	('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'RELIGION', 7),	('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'CONQUEST', 4),
('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'SCIENCE', 4),	('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'CULTURE', 4),	('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'RELIGION', 3),	('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'CONQUEST', 2),
('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'SCIENCE', 2),	('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'CULTURE', 2),	('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'RELIGION', 1),	('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'CONQUEST', 9),
('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'SCIENCE', 7),	('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'CULTURE', 3),	('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'RELIGION', 1),	('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'CONQUEST', 4),
('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'SCIENCE', 5),	('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'CULTURE', 7),	('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'RELIGION', 3),	('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'CONQUEST', 1);

-- POLICIES
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
	('POLICY_AESTHETICS', 'POLICY', 'ECONOMIC', 'CULTURE', 7),		
			('POLICY_AFTER_ACTION_REPORTS', 'POLICY', 'MILITARY', 'CONQUEST', 5),
			('POLICY_AGOGE', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_ARSENAL_OF_DEMOCRACY', 'POLICY', 'DIPLOMATIC', 'SCIENCE', 2),	('POLICY_ARSENAL_OF_DEMOCRACY', 'POLICY', 'DIPLOMATIC', 'CULTURE', 1),	('POLICY_ARSENAL_OF_DEMOCRACY', 'POLICY', 'DIPLOMATIC', 'RELIGION', 1),	('POLICY_ARSENAL_OF_DEMOCRACY', 'POLICY', 'DIPLOMATIC', 'CONQUEST', 2),
			
			
			
			('POLICY_CHIVALRY', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_CIVIL_PRESTIGE', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_CIVIL_PRESTIGE', 'POLICY', 'ECONOMIC', 'CULTURE', 1),	('POLICY_CIVIL_PRESTIGE', 'POLICY', 'ECONOMIC', 'RELIGION', 1),	('POLICY_CIVIL_PRESTIGE', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
	('POLICY_COLLECTIVE_ACTIVISM', 'POLICY', 'DIPLOMATIC', 'CULTURE', 6),		
('POLICY_COLLECTIVISM', 'POLICY', 'DARKAGE', 'SCIENCE', 1),	('POLICY_COLLECTIVISM', 'POLICY', 'DARKAGE', 'CULTURE', -2),		('POLICY_COLLECTIVISM', 'POLICY', 'DARKAGE', 'CONQUEST', 2),
('POLICY_COLLECTIVIZATION', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_COLLECTIVIZATION', 'POLICY', 'ECONOMIC', 'CULTURE', 1),		
			('POLICY_COLONIAL_OFFICES', 'POLICY', 'ECONOMIC', 'CONQUEST', 4),
			('POLICY_COLONIAL_TAXES', 'POLICY', 'ECONOMIC', 'CONQUEST', 4),
('POLICY_COLONIZATION', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),	('POLICY_COLONIZATION', 'POLICY', 'ECONOMIC', 'CULTURE', 2),	('POLICY_COLONIZATION', 'POLICY', 'ECONOMIC', 'RELIGION', 2),	('POLICY_COLONIZATION', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
			('POLICY_COMMUNICATIONS_OFFICE', 'POLICY', 'DIPLOMATIC', 'CONQUEST', 3),
			
			
('POLICY_CORVEE', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_CORVEE', 'POLICY', 'ECONOMIC', 'CULTURE', 2),	('POLICY_CORVEE', 'POLICY', 'ECONOMIC', 'RELIGION', 2),	('POLICY_CORVEE', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
('POLICY_CRAFTSMEN', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),			('POLICY_CRAFTSMEN', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
			('POLICY_CRYPTOGRAPHY', 'POLICY', 'DIPLOMATIC', 'CONQUEST', 1),
			
			
			
('POLICY_ECOMMERCE', 'POLICY', 'ECONOMIC', 'SCIENCE', 3),			
			
			('POLICY_ELITE_FORCES', 'POLICY', 'DARKAGE', 'CONQUEST', 5),
('POLICY_EXPROPRIATION', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),	('POLICY_EXPROPRIATION', 'POLICY', 'ECONOMIC', 'CULTURE', 2),	('POLICY_EXPROPRIATION', 'POLICY', 'ECONOMIC', 'RELIGION', 2),	('POLICY_EXPROPRIATION', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
			('POLICY_FEUDAL_CONTRACT', 'POLICY', 'MILITARY', 'CONQUEST', 6),
			('POLICY_FINEST_HOUR', 'POLICY', 'MILITARY', 'CONQUEST', 7),
('POLICY_FIVE_YEAR_PLAN', 'POLICY', 'ECONOMIC', 'SCIENCE', 6),			('POLICY_FIVE_YEAR_PLAN', 'POLICY', 'ECONOMIC', 'CONQUEST', 3),
('POLICY_FREE_MARKET', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_FREE_MARKET', 'POLICY', 'ECONOMIC', 'CULTURE', 1),	('POLICY_FREE_MARKET', 'POLICY', 'ECONOMIC', 'RELIGION', 1),	('POLICY_FREE_MARKET', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
	('POLICY_FRESCOES', 'POLICY', 'GREAT_PERSON', 'CULTURE', 5),		
		('POLICY_GOD_KING', 'POLICY', 'ECONOMIC', 'RELIGION', 4),	
('POLICY_GOTHIC_ARCHITECTURE', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),	('POLICY_GOTHIC_ARCHITECTURE', 'POLICY', 'ECONOMIC', 'CULTURE', 3),	('POLICY_GOTHIC_ARCHITECTURE', 'POLICY', 'ECONOMIC', 'RELIGION', 3),	('POLICY_GOTHIC_ARCHITECTURE', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
('POLICY_GOV_AUTOCRACY', 'POLICY', 'WILDCARD', 'SCIENCE', 2),	('POLICY_GOV_AUTOCRACY', 'POLICY', 'WILDCARD', 'CULTURE', 4),	('POLICY_GOV_AUTOCRACY', 'POLICY', 'WILDCARD', 'RELIGION', 2),	('POLICY_GOV_AUTOCRACY', 'POLICY', 'WILDCARD', 'CONQUEST', 4),
('POLICY_GOV_CLASSICAL_REPUBLIC', 'POLICY', 'WILDCARD', 'SCIENCE', 3),	('POLICY_GOV_CLASSICAL_REPUBLIC', 'POLICY', 'WILDCARD', 'CULTURE', 3),	('POLICY_GOV_CLASSICAL_REPUBLIC', 'POLICY', 'WILDCARD', 'RELIGION', 2),	('POLICY_GOV_CLASSICAL_REPUBLIC', 'POLICY', 'WILDCARD', 'CONQUEST', 1),
('POLICY_GOV_COMMUNISM', 'POLICY', 'WILDCARD', 'SCIENCE', 7),	('POLICY_GOV_COMMUNISM', 'POLICY', 'WILDCARD', 'CULTURE', 3),	('POLICY_GOV_COMMUNISM', 'POLICY', 'WILDCARD', 'RELIGION', 1),	('POLICY_GOV_COMMUNISM', 'POLICY', 'WILDCARD', 'CONQUEST', 4),
('POLICY_GOV_DEMOCRACY', 'POLICY', 'WILDCARD', 'SCIENCE', 5),	('POLICY_GOV_DEMOCRACY', 'POLICY', 'WILDCARD', 'CULTURE', 7),	('POLICY_GOV_DEMOCRACY', 'POLICY', 'WILDCARD', 'RELIGION', 3),	('POLICY_GOV_DEMOCRACY', 'POLICY', 'WILDCARD', 'CONQUEST', 1),
('POLICY_GOV_FASCISM', 'POLICY', 'WILDCARD', 'SCIENCE', 2),	('POLICY_GOV_FASCISM', 'POLICY', 'WILDCARD', 'CULTURE', 2),	('POLICY_GOV_FASCISM', 'POLICY', 'WILDCARD', 'RELIGION', 1),	('POLICY_GOV_FASCISM', 'POLICY', 'WILDCARD', 'CONQUEST', 9),
('POLICY_GOV_MERCHANT_REPUBLIC', 'POLICY', 'WILDCARD', 'SCIENCE', 4),	('POLICY_GOV_MERCHANT_REPUBLIC', 'POLICY', 'WILDCARD', 'CULTURE', 4),	('POLICY_GOV_MERCHANT_REPUBLIC', 'POLICY', 'WILDCARD', 'RELIGION', 3),	('POLICY_GOV_MERCHANT_REPUBLIC', 'POLICY', 'WILDCARD', 'CONQUEST', 2),
('POLICY_GOV_MONARCHY', 'POLICY', 'WILDCARD', 'SCIENCE', 2),	('POLICY_GOV_MONARCHY', 'POLICY', 'WILDCARD', 'CULTURE', 2),	('POLICY_GOV_MONARCHY', 'POLICY', 'WILDCARD', 'RELIGION', 2),	('POLICY_GOV_MONARCHY', 'POLICY', 'WILDCARD', 'CONQUEST', 4),
('POLICY_GOV_OLIGARCHY', 'POLICY', 'WILDCARD', 'SCIENCE', 2),	('POLICY_GOV_OLIGARCHY', 'POLICY', 'WILDCARD', 'CULTURE', 2),	('POLICY_GOV_OLIGARCHY', 'POLICY', 'WILDCARD', 'RELIGION', 2),	('POLICY_GOV_OLIGARCHY', 'POLICY', 'WILDCARD', 'CONQUEST', 6),
('POLICY_GOV_THEOCRACY', 'POLICY', 'WILDCARD', 'SCIENCE', 2),	('POLICY_GOV_THEOCRACY', 'POLICY', 'WILDCARD', 'CULTURE', 2),	('POLICY_GOV_THEOCRACY', 'POLICY', 'WILDCARD', 'RELIGION', 7),	('POLICY_GOV_THEOCRACY', 'POLICY', 'WILDCARD', 'CONQUEST', 4),
			('POLICY_GRANDE_ARMEE', 'POLICY', 'MILITARY', 'CONQUEST', 6),
	('POLICY_GRAND_OPERA', 'POLICY', 'ECONOMIC', 'CULTURE', 7),		
			
	('POLICY_HERITAGE_TOURISM', 'POLICY', 'ECONOMIC', 'CULTURE', 8),		
('POLICY_ILKUM', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_ILKUM', 'POLICY', 'ECONOMIC', 'CULTURE', 1),	('POLICY_ILKUM', 'POLICY', 'ECONOMIC', 'RELIGION', 1),	('POLICY_ILKUM', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
('POLICY_INQUISITION', 'POLICY', 'DARKAGE', 'SCIENCE', -2),			
('POLICY_INSPIRATION', 'POLICY', 'GREAT_PERSON', 'SCIENCE', 5),			
('POLICY_INSULAE', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_INSULAE', 'POLICY', 'ECONOMIC', 'CULTURE', 1),		
('POLICY_INTEGRATED_SPACE_CELL', 'POLICY', 'MILITARY', 'SCIENCE', 7),			
('POLICY_INTERNATIONAL_SPACE_AGENCY', 'POLICY', 'DIPLOMATIC', 'SCIENCE', 6),			
			('POLICY_INTERNATIONAL_WATERS', 'POLICY', 'MILITARY', 'CONQUEST', 3),
('POLICY_INVENTION', 'POLICY', 'GREAT_PERSON', 'SCIENCE', 2),			('POLICY_INVENTION', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 2),
('POLICY_ISOLATIONISM', 'POLICY', 'DARKAGE', 'SCIENCE', 2),	('POLICY_ISOLATIONISM', 'POLICY', 'DARKAGE', 'CULTURE', 1),		('POLICY_ISOLATIONISM', 'POLICY', 'DARKAGE', 'CONQUEST', 2),
			
			
			('POLICY_LETTERS_OF_MARQUE', 'POLICY', 'DARKAGE', 'CONQUEST', 5),
			('POLICY_LEVEE_EN_MASSE', 'POLICY', 'MILITARY', 'CONQUEST', 4),
			
			('POLICY_LIGHTNING_WARFARE', 'POLICY', 'MILITARY', 'CONQUEST', 7),
			
			('POLICY_LIMITANEI', 'POLICY', 'MILITARY', 'CONQUEST', 4),
	('POLICY_LITERARY_TRADITION', 'POLICY', 'GREAT_PERSON', 'CULTURE', 5),		
			('POLICY_LOGISTICS', 'POLICY', 'MILITARY', 'CONQUEST', 5),
			('POLICY_MACHIAVELLIANISM', 'POLICY', 'DIPLOMATIC', 'CONQUEST', 3),
			('POLICY_MANEUVER', 'POLICY', 'MILITARY', 'CONQUEST', 7),
			('POLICY_MARITIME_INDUSTRIES', 'POLICY', 'MILITARY', 'CONQUEST', 3),
('POLICY_MARKET_ECONOMY', 'POLICY', 'ECONOMIC', 'SCIENCE', 3),	('POLICY_MARKET_ECONOMY', 'POLICY', 'ECONOMIC', 'CULTURE', 3),		
			('POLICY_MARTIAL_LAW', 'POLICY', 'MILITARY', 'CONQUEST', 7),
('POLICY_MEDINA_QUARTER', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),	('POLICY_MEDINA_QUARTER', 'POLICY', 'ECONOMIC', 'CULTURE', 2),	('POLICY_MEDINA_QUARTER', 'POLICY', 'ECONOMIC', 'RELIGION', 2),	('POLICY_MEDINA_QUARTER', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
			
	('POLICY_MERITOCRACY', 'POLICY', 'ECONOMIC', 'CULTURE', 5),		
			('POLICY_MILITARY_FIRST', 'POLICY', 'MILITARY', 'CONQUEST', 6),
			('POLICY_MILITARY_ORGANIZATION', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 8),
('POLICY_MILITARY_RESEARCH', 'POLICY', 'MILITARY', 'SCIENCE', 3),			
('POLICY_MONASTICISM', 'POLICY', 'DARKAGE', 'SCIENCE', 4),	('POLICY_MONASTICISM', 'POLICY', 'DARKAGE', 'CULTURE', -2),		
			('POLICY_NATIONAL_IDENTITY', 'POLICY', 'MILITARY', 'CONQUEST', 7),
			('POLICY_NATIVE_CONQUEST', 'POLICY', 'MILITARY', 'CONQUEST', 5),
('POLICY_NATURAL_PHILOSOPHY', 'POLICY', 'ECONOMIC', 'SCIENCE', 7),			
			
			('POLICY_NAVIGATION', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 3),
('POLICY_NEW_DEAL', 'POLICY', 'ECONOMIC', 'SCIENCE', 3),	('POLICY_NEW_DEAL', 'POLICY', 'ECONOMIC', 'CULTURE', 3),	('POLICY_NEW_DEAL', 'POLICY', 'ECONOMIC', 'RELIGION', 3),	('POLICY_NEW_DEAL', 'POLICY', 'ECONOMIC', 'CONQUEST', 3),
('POLICY_NOBEL_PRIZE', 'POLICY', 'GREAT_PERSON', 'SCIENCE', 5),			
('POLICY_NUCLEAR_ESPIONAGE', 'POLICY', 'DIPLOMATIC', 'SCIENCE', 4),			
	('POLICY_ONLINE_COMMUNITIES', 'POLICY', 'ECONOMIC', 'CULTURE', 8),		
			('POLICY_PATRIOTIC_WAR', 'POLICY', 'MILITARY', 'CONQUEST', 3),
			
			('POLICY_PRAETORIUM', 'POLICY', 'DIPLOMATIC', 'CONQUEST', 1),
			('POLICY_PRESS_GANGS', 'POLICY', 'MILITARY', 'CONQUEST', 4),
			('POLICY_PROFESSIONAL_ARMY', 'POLICY', 'MILITARY', 'CONQUEST', 5),
			('POLICY_PROPAGANDA', 'POLICY', 'MILITARY', 'CONQUEST', 7),
('POLICY_PUBLIC_TRANSPORT', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),	('POLICY_PUBLIC_TRANSPORT', 'POLICY', 'ECONOMIC', 'CULTURE', 2),	('POLICY_PUBLIC_TRANSPORT', 'POLICY', 'ECONOMIC', 'RELIGION', 2),	('POLICY_PUBLIC_TRANSPORT', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
('POLICY_PUBLIC_WORKS', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),	('POLICY_PUBLIC_WORKS', 'POLICY', 'ECONOMIC', 'CULTURE', 2),	('POLICY_PUBLIC_WORKS', 'POLICY', 'ECONOMIC', 'RELIGION', 2),	('POLICY_PUBLIC_WORKS', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
('POLICY_RAID', 'POLICY', 'MILITARY', 'SCIENCE', 2),	('POLICY_RAID', 'POLICY', 'MILITARY', 'CULTURE', 2),	('POLICY_RAID', 'POLICY', 'MILITARY', 'RELIGION', 2),	('POLICY_RAID', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_RAJ', 'POLICY', 'DIPLOMATIC', 'SCIENCE', 2),	('POLICY_RAJ', 'POLICY', 'DIPLOMATIC', 'CULTURE', 2),	('POLICY_RAJ', 'POLICY', 'DIPLOMATIC', 'RELIGION', 2),	
	('POLICY_RATIONALISM', 'POLICY', 'ECONOMIC', 'CULTURE', 7),		
		('POLICY_RELIGIOUS_ORDERS', 'POLICY', 'ECONOMIC', 'RELIGION', 7),	
			('POLICY_RESOURCE_MANAGEMENT', 'POLICY', 'ECONOMIC', 'CONQUEST', 6),
			
		('POLICY_REVELATION', 'POLICY', 'GREAT_PERSON', 'RELIGION', 8),	
('POLICY_ROBBER_BARONS', 'POLICY', 'DARKAGE', 'SCIENCE', 4),			('POLICY_ROBBER_BARONS', 'POLICY', 'DARKAGE', 'CONQUEST', 4),
			('POLICY_ROGUE_STATE', 'POLICY', 'DARKAGE', 'CONQUEST', 5),
	('POLICY_SATELLITE_BROADCASTS', 'POLICY', 'ECONOMIC', 'CULTURE', 8),		
		('POLICY_SCRIPTURE', 'POLICY', 'ECONOMIC', 'RELIGION', 6),	
			('POLICY_SECOND_STRIKE_CAPABILITY', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_SERFDOM', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_SERFDOM', 'POLICY', 'ECONOMIC', 'CULTURE', 1),	('POLICY_SERFDOM', 'POLICY', 'ECONOMIC', 'RELIGION', 1),	('POLICY_SERFDOM', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
		('POLICY_SIMULTANEUM', 'POLICY', 'ECONOMIC', 'RELIGION', 7),	
('POLICY_SKYSCRAPERS', 'POLICY', 'ECONOMIC', 'SCIENCE', 2),	('POLICY_SKYSCRAPERS', 'POLICY', 'ECONOMIC', 'CULTURE', 3),	('POLICY_SKYSCRAPERS', 'POLICY', 'ECONOMIC', 'RELIGION', 3),	('POLICY_SKYSCRAPERS', 'POLICY', 'ECONOMIC', 'CONQUEST', 2),
('POLICY_SPORTS_MEDIA', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_SPORTS_MEDIA', 'POLICY', 'ECONOMIC', 'CULTURE', 6),	('POLICY_SPORTS_MEDIA', 'POLICY', 'ECONOMIC', 'RELIGION', 1),	('POLICY_SPORTS_MEDIA', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
			('POLICY_STRATEGIC_AIR_FORCE', 'POLICY', 'MILITARY', 'CONQUEST', 5),
			('POLICY_STRATEGOS', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 5),
			
	('POLICY_SYMPHONIES', 'POLICY', 'GREAT_PERSON', 'CULTURE', 6),		
('POLICY_THIRD_ALTERNATIVE', 'POLICY', 'ECONOMIC', 'SCIENCE', 6),			
('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'SCIENCE', 2),	('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'CULTURE', 2),	('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'RELIGION', 2),	('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_TOWN_CHARTERS', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_TOWN_CHARTERS', 'POLICY', 'ECONOMIC', 'CULTURE', 1),	('POLICY_TOWN_CHARTERS', 'POLICY', 'ECONOMIC', 'RELIGION', 1),	('POLICY_TOWN_CHARTERS', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
('POLICY_TRADE_CONFEDERATION', 'POLICY', 'ECONOMIC', 'SCIENCE', 4),	('POLICY_TRADE_CONFEDERATION', 'POLICY', 'ECONOMIC', 'CULTURE', 4),		
			
		('POLICY_TRIANGULAR_TRADE', 'POLICY', 'ECONOMIC', 'RELIGION', 3),	
			('POLICY_TWILIGHT_VALOR', 'POLICY', 'DARKAGE', 'CONQUEST', 3),
('POLICY_URBAN_PLANNING', 'POLICY', 'ECONOMIC', 'SCIENCE', 1),	('POLICY_URBAN_PLANNING', 'POLICY', 'ECONOMIC', 'CULTURE', 1),	('POLICY_URBAN_PLANNING', 'POLICY', 'ECONOMIC', 'RELIGION', 1),	('POLICY_URBAN_PLANNING', 'POLICY', 'ECONOMIC', 'CONQUEST', 1),
			('POLICY_VETERANCY', 'POLICY', 'MILITARY', 'CONQUEST', 4),
			('POLICY_WARS_OF_RELIGION', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_WISSELBANKEN', 'POLICY', 'DIPLOMATIC', 'SCIENCE', 2),	('POLICY_WISSELBANKEN', 'POLICY', 'DIPLOMATIC', 'CULTURE', 1),	('POLICY_WISSELBANKEN', 'POLICY', 'DIPLOMATIC', 'RELIGION', 1),	('POLICY_WISSELBANKEN', 'POLICY', 'DIPLOMATIC', 'CONQUEST', 2);

-- CityStates
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
	('CULTURAL', 'CityState', '', 'CULTURE', 7),		
('INDUSTRIAL', 'CityState', '', 'SCIENCE', 4),	('INDUSTRIAL', 'CityState', '', 'CULTURE', 2),	('INDUSTRIAL', 'CityState', '', 'RELIGION', 2),	('INDUSTRIAL', 'CityState', '', 'CONQUEST', 3),
			('MILITARISTIC', 'CityState', '', 'CONQUEST', 7),
		('RELIGIOUS', 'CityState', '', 'RELIGION', 7),	
('SCIENTIFIC', 'CityState', '', 'SCIENCE', 7),
('TRADE', 'CityState', '', 'SCIENCE', 1),	('TRADE', 'CityState', '', 'CULTURE', 1),	('TRADE', 'CityState', '', 'RELIGION', 1),	('TRADE', 'CityState', '', 'CONQUEST', 1);
			
-- BELIEFS
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
		('BELIEF_BURIAL_GROUNDS', 'BELIEF', 'ENHANCER', 'RELIGION', 3),	
	('BELIEF_CATHEDRAL', 'BELIEF', 'WORSHIP', 'CULTURE', 2),	('BELIEF_CATHEDRAL', 'BELIEF', 'WORSHIP', 'RELIGION', 5),	
	('BELIEF_CHORAL_MUSIC', 'BELIEF', 'FOLLOWER', 'CULTURE', 4),		
		('BELIEF_CHURCH_PROPERTY', 'BELIEF', 'FOUNDER', 'RELIGION', 3),	
('BELIEF_CITY_PATRON_GODDESS', 'BELIEF', 'PANTHEON', 'SCIENCE', 1),	('BELIEF_CITY_PATRON_GODDESS', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_CITY_PATRON_GODDESS', 'BELIEF', 'PANTHEON', 'RELIGION', 1),	
('BELIEF_CROSS_CULTURAL_DIALOGUE', 'BELIEF', 'FOUNDER', 'SCIENCE', 3),		('BELIEF_CROSS_CULTURAL_DIALOGUE', 'BELIEF', 'FOUNDER', 'RELIGION', 3),	
		('BELIEF_DANCE_OF_THE_AURORA', 'BELIEF', 'PANTHEON', 'RELIGION', 4),	
		('BELIEF_DAR_E_MEHR', 'BELIEF', 'WORSHIP', 'RELIGION', 6),	
			
		('BELIEF_DESERT_FOLKLORE', 'BELIEF', 'PANTHEON', 'RELIGION', 5),	
	('BELIEF_DIVINE_INSPIRATION', 'BELIEF', 'FOLLOWER', 'CULTURE', 3),	('BELIEF_DIVINE_INSPIRATION', 'BELIEF', 'FOLLOWER', 'RELIGION', 4),	
('BELIEF_DIVINE_SPARK', 'BELIEF', 'PANTHEON', 'SCIENCE', 3),	('BELIEF_DIVINE_SPARK', 'BELIEF', 'PANTHEON', 'CULTURE', 3),	('BELIEF_DIVINE_SPARK', 'BELIEF', 'PANTHEON', 'RELIGION', 3),	
		('BELIEF_EARTH_GODDESS', 'BELIEF', 'PANTHEON', 'RELIGION', 9),	
('BELIEF_FEED_THE_WORLD', 'BELIEF', 'FOLLOWER', 'SCIENCE', 3),	('BELIEF_FEED_THE_WORLD', 'BELIEF', 'FOLLOWER', 'CULTURE', 2),		
('BELIEF_FERTILITY_RITES', 'BELIEF', 'PANTHEON', 'SCIENCE', 2),	('BELIEF_FERTILITY_RITES', 'BELIEF', 'PANTHEON', 'CULTURE', 2),	('BELIEF_FERTILITY_RITES', 'BELIEF', 'PANTHEON', 'RELIGION', 2),	('BELIEF_FERTILITY_RITES', 'BELIEF', 'PANTHEON', 'CONQUEST', 2),
('BELIEF_GODDESS_OF_FESTIVALS', 'BELIEF', 'PANTHEON', 'SCIENCE', 1),	('BELIEF_GODDESS_OF_FESTIVALS', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_GODDESS_OF_FESTIVALS', 'BELIEF', 'PANTHEON', 'RELIGION', 1),	('BELIEF_GODDESS_OF_FESTIVALS', 'BELIEF', 'PANTHEON', 'CONQUEST', 1),
		('BELIEF_GODDESS_OF_THE_HARVEST', 'BELIEF', 'PANTHEON', 'RELIGION', 4),	
('BELIEF_GODDESS_OF_THE_HUNT', 'BELIEF', 'PANTHEON', 'SCIENCE', 1),	('BELIEF_GODDESS_OF_THE_HUNT', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_GODDESS_OF_THE_HUNT', 'BELIEF', 'PANTHEON', 'RELIGION', 1),	('BELIEF_GODDESS_OF_THE_HUNT', 'BELIEF', 'PANTHEON', 'CONQUEST', 1),
('BELIEF_GOD_OF_CRAFTSMEN', 'BELIEF', 'PANTHEON', 'SCIENCE', 3),	('BELIEF_GOD_OF_CRAFTSMEN', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_GOD_OF_CRAFTSMEN', 'BELIEF', 'PANTHEON', 'RELIGION', 1),	('BELIEF_GOD_OF_CRAFTSMEN', 'BELIEF', 'PANTHEON', 'CONQUEST', 3),
		('BELIEF_GOD_OF_HEALING', 'BELIEF', 'PANTHEON', 'RELIGION', 8),	('BELIEF_GOD_OF_HEALING', 'BELIEF', 'PANTHEON', 'CONQUEST', 3),
			('BELIEF_GOD_OF_THE_FORGE', 'BELIEF', 'PANTHEON', 'CONQUEST', 8),
	('BELIEF_GOD_OF_THE_OPEN_SKY', 'BELIEF', 'PANTHEON', 'CULTURE', 5),		
('BELIEF_GOD_OF_THE_SEA', 'BELIEF', 'PANTHEON', 'SCIENCE', 2),	('BELIEF_GOD_OF_THE_SEA', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_GOD_OF_THE_SEA', 'BELIEF', 'PANTHEON', 'RELIGION', 1),	('BELIEF_GOD_OF_THE_SEA', 'BELIEF', 'PANTHEON', 'CONQUEST', 2),
			('BELIEF_GOD_OF_WAR', 'BELIEF', 'PANTHEON', 'CONQUEST', 4),
('BELIEF_GURDWARA', 'BELIEF', 'WORSHIP', 'SCIENCE', 2),	('BELIEF_GURDWARA', 'BELIEF', 'WORSHIP', 'CULTURE', 1),	('BELIEF_GURDWARA', 'BELIEF', 'WORSHIP', 'RELIGION', 6),	('BELIEF_GURDWARA', 'BELIEF', 'WORSHIP', 'CONQUEST', 1),
		('BELIEF_HOLY_ORDER', 'BELIEF', 'ENHANCER', 'RELIGION', 6),	
		('BELIEF_INITIATION_RITES', 'BELIEF', 'PANTHEON', 'RELIGION', 2),	
		('BELIEF_ITINERANT_PREACHERS', 'BELIEF', 'ENHANCER', 'RELIGION', 6),	
('BELIEF_JESUIT_EDUCATION', 'BELIEF', 'FOLLOWER', 'SCIENCE', 8),	('BELIEF_JESUIT_EDUCATION', 'BELIEF', 'FOLLOWER', 'CULTURE', 8),		
		('BELIEF_JUST_WAR', 'BELIEF', 'ENHANCER', 'RELIGION', 4),	('BELIEF_JUST_WAR', 'BELIEF', 'ENHANCER', 'CONQUEST', 7),
('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES', 'BELIEF', 'PANTHEON', 'SCIENCE', 2),	('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES', 'BELIEF', 'PANTHEON', 'RELIGION', 1),	('BELIEF_LADY_OF_THE_REEDS_AND_MARSHES', 'BELIEF', 'PANTHEON', 'CONQUEST', 2),
	('BELIEF_LAY_MINISTRY', 'BELIEF', 'FOUNDER', 'CULTURE', 3),	('BELIEF_LAY_MINISTRY', 'BELIEF', 'FOUNDER', 'RELIGION', 3),	
('BELIEF_MEETING_HOUSE', 'BELIEF', 'WORSHIP', 'SCIENCE', 2),		('BELIEF_MEETING_HOUSE', 'BELIEF', 'WORSHIP', 'RELIGION', 5),	('BELIEF_MEETING_HOUSE', 'BELIEF', 'WORSHIP', 'CONQUEST', 2),
		('BELIEF_MISSIONARY_ZEAL', 'BELIEF', 'ENHANCER', 'RELIGION', 8),	
		('BELIEF_MONASTIC_ISOLATION', 'BELIEF', 'ENHANCER', 'RELIGION', 7),	
('BELIEF_MONUMENT_TO_THE_GODS', 'BELIEF', 'PANTHEON', 'SCIENCE', 2),	('BELIEF_MONUMENT_TO_THE_GODS', 'BELIEF', 'PANTHEON', 'CULTURE', 2),	('BELIEF_MONUMENT_TO_THE_GODS', 'BELIEF', 'PANTHEON', 'RELIGION', 2),	('BELIEF_MONUMENT_TO_THE_GODS', 'BELIEF', 'PANTHEON', 'CONQUEST', 2),
		('BELIEF_MOSQUE', 'BELIEF', 'WORSHIP', 'RELIGION', 9),	
	('BELIEF_ORAL_TRADITION', 'BELIEF', 'PANTHEON', 'CULTURE', 3),		
('BELIEF_PAGODA', 'BELIEF', 'WORSHIP', 'SCIENCE', 2),	('BELIEF_PAGODA', 'BELIEF', 'WORSHIP', 'CULTURE', 1),	('BELIEF_PAGODA', 'BELIEF', 'WORSHIP', 'RELIGION', 5),	('BELIEF_PAGODA', 'BELIEF', 'WORSHIP', 'CONQUEST', 1),
('BELIEF_PAPAL_PRIMACY', 'BELIEF', 'FOUNDER', 'SCIENCE', 5),	('BELIEF_PAPAL_PRIMACY', 'BELIEF', 'FOUNDER', 'CULTURE', 5),	('BELIEF_PAPAL_PRIMACY', 'BELIEF', 'FOUNDER', 'RELIGION', 5),	('BELIEF_PAPAL_PRIMACY', 'BELIEF', 'FOUNDER', 'CONQUEST', 5),
		('BELIEF_PILGRIMAGE', 'BELIEF', 'FOUNDER', 'RELIGION', 3),	
		('BELIEF_RELIGIOUS_COLONIZATION', 'BELIEF', 'ENHANCER', 'RELIGION', 4),	
('BELIEF_RELIGIOUS_COMMUNITY', 'BELIEF', 'FOLLOWER', 'SCIENCE', 2),	('BELIEF_RELIGIOUS_COMMUNITY', 'BELIEF', 'FOLLOWER', 'CULTURE', 1),	('BELIEF_RELIGIOUS_COMMUNITY', 'BELIEF', 'FOLLOWER', 'RELIGION', 1),	('BELIEF_RELIGIOUS_COMMUNITY', 'BELIEF', 'FOLLOWER', 'CONQUEST', 1),
		('BELIEF_RELIGIOUS_IDOLS', 'BELIEF', 'PANTHEON', 'RELIGION', 5),	
('BELIEF_RELIGIOUS_SETTLEMENTS', 'BELIEF', 'PANTHEON', 'SCIENCE', 1),	('BELIEF_RELIGIOUS_SETTLEMENTS', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_RELIGIOUS_SETTLEMENTS', 'BELIEF', 'PANTHEON', 'RELIGION', 1),	('BELIEF_RELIGIOUS_SETTLEMENTS', 'BELIEF', 'PANTHEON', 'CONQUEST', 3),
		('BELIEF_RELIGIOUS_UNITY', 'BELIEF', 'FOUNDER', 'RELIGION', 4),	
	('BELIEF_RELIQUARIES', 'BELIEF', 'FOLLOWER', 'CULTURE', 7),	('BELIEF_RELIQUARIES', 'BELIEF', 'FOLLOWER', 'RELIGION', 3),	
('BELIEF_RIVER_GODDESS', 'BELIEF', 'PANTHEON', 'SCIENCE', 1),	('BELIEF_RIVER_GODDESS', 'BELIEF', 'PANTHEON', 'CULTURE', 1),	('BELIEF_RIVER_GODDESS', 'BELIEF', 'PANTHEON', 'RELIGION', 3),	('BELIEF_RIVER_GODDESS', 'BELIEF', 'PANTHEON', 'CONQUEST', 1),
		('BELIEF_SACRED_PATH', 'BELIEF', 'PANTHEON', 'RELIGION', 3),	
		('BELIEF_SCRIPTURE', 'BELIEF', 'ENHANCER', 'RELIGION', 8),	
('BELIEF_STEWARDSHIP', 'BELIEF', 'FOUNDER', 'SCIENCE', 6),			
		('BELIEF_STONE_CIRCLES', 'BELIEF', 'PANTHEON', 'RELIGION', 5),	
		('BELIEF_STUPA', 'BELIEF', 'WORSHIP', 'RELIGION', 5),	
		('BELIEF_SYNAGOGUE', 'BELIEF', 'WORSHIP', 'RELIGION', 6),	
('BELIEF_TITHE', 'BELIEF', 'FOUNDER', 'SCIENCE', 1),	('BELIEF_TITHE', 'BELIEF', 'FOUNDER', 'CULTURE', 1),	('BELIEF_TITHE', 'BELIEF', 'FOUNDER', 'RELIGION', 2),	('BELIEF_TITHE', 'BELIEF', 'FOUNDER', 'CONQUEST', 1),
		('BELIEF_WARRIOR_MONKS', 'BELIEF', 'FOLLOWER', 'RELIGION', 3),	('BELIEF_WARRIOR_MONKS', 'BELIEF', 'FOLLOWER', 'CONQUEST', 7),
('BELIEF_WAT', 'BELIEF', 'WORSHIP', 'SCIENCE', 4),		('BELIEF_WAT', 'BELIEF', 'WORSHIP', 'RELIGION', 5),	
('BELIEF_WORK_ETHIC', 'BELIEF', 'FOLLOWER', 'SCIENCE', 4),	('BELIEF_WORK_ETHIC', 'BELIEF', 'FOLLOWER', 'CULTURE', 2),	('BELIEF_WORK_ETHIC', 'BELIEF', 'FOLLOWER', 'RELIGION', 3),	('BELIEF_WORK_ETHIC', 'BELIEF', 'FOLLOWER', 'CONQUEST', 3),
	('BELIEF_WORLD_CHURCH', 'BELIEF', 'FOUNDER', 'CULTURE', 4),	('BELIEF_WORLD_CHURCH', 'BELIEF', 'FOUNDER', 'RELIGION', 4),	
('BELIEF_ZEN_MEDITATION', 'BELIEF', 'FOLLOWER', 'SCIENCE', 1),	('BELIEF_ZEN_MEDITATION', 'BELIEF', 'FOLLOWER', 'CULTURE', 1),	('BELIEF_ZEN_MEDITATION', 'BELIEF', 'FOLLOWER', 'RELIGION', 1),	('BELIEF_ZEN_MEDITATION', 'BELIEF', 'FOLLOWER', 'CONQUEST', 1);

-- Wonders
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
			('BUILDING_ALHAMBRA', 'Wonder', '', 'CONQUEST', 5),
('BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION', 'Wonder', '', 'SCIENCE', 8),			
('BUILDING_ANGKOR_WAT', 'Wonder', '', 'SCIENCE', 1),		('BUILDING_ANGKOR_WAT', 'Wonder', '', 'RELIGION', 2),	
	('BUILDING_APADANA', 'Wonder', '', 'CULTURE', 2),		
('BUILDING_BIG_BEN', 'Wonder', '', 'SCIENCE', 2),	('BUILDING_BIG_BEN', 'Wonder', '', 'CULTURE', 2),	('BUILDING_BIG_BEN', 'Wonder', '', 'RELIGION', 2),	
	('BUILDING_BOLSHOI_THEATRE', 'Wonder', '', 'CULTURE', 8),		
	('BUILDING_BROADWAY', 'Wonder', '', 'CULTURE', 8),		
('BUILDING_CASA_DE_CONTRATACION', 'Wonder', '', 'SCIENCE', 2),		('BUILDING_CASA_DE_CONTRATACION', 'Wonder', '', 'RELIGION', 2),	
	('BUILDING_CHICHEN_ITZA', 'Wonder', '', 'CULTURE', 2),		
	('BUILDING_COLOSSEUM', 'Wonder', '', 'CULTURE', 3),		
			('BUILDING_COLOSSUS', 'Wonder', '', 'CONQUEST', 1),
	('BUILDING_CRISTO_REDENTOR', 'Wonder', '', 'CULTURE', 9),		
	('BUILDING_EIFFEL_TOWER', 'Wonder', '', 'CULTURE', 6),		
('BUILDING_ESTADIO_DO_MARACANA', 'Wonder', '', 'SCIENCE', 2),	('BUILDING_ESTADIO_DO_MARACANA', 'Wonder', '', 'CULTURE', 4),	('BUILDING_ESTADIO_DO_MARACANA', 'Wonder', '', 'RELIGION', 2),	('BUILDING_ESTADIO_DO_MARACANA', 'Wonder', '', 'CONQUEST', 2),
('BUILDING_FORBIDDEN_CITY', 'Wonder', '', 'SCIENCE', 3),	('BUILDING_FORBIDDEN_CITY', 'Wonder', '', 'CULTURE', 4),	('BUILDING_FORBIDDEN_CITY', 'Wonder', '', 'RELIGION', 3),	('BUILDING_FORBIDDEN_CITY', 'Wonder', '', 'CONQUEST', 3),
('BUILDING_GREAT_LIBRARY', 'Wonder', '', 'SCIENCE', 6),	('BUILDING_GREAT_LIBRARY', 'Wonder', '', 'CULTURE', 3),		
			('BUILDING_GREAT_LIGHTHOUSE', 'Wonder', '', 'CONQUEST', 5),
			
		('BUILDING_HAGIA_SOPHIA', 'Wonder', '', 'RELIGION', 7),	
('BUILDING_HALICARNASSUS_MAUSOLEUM', 'Wonder', '', 'SCIENCE', 3),			
('BUILDING_HANGING_GARDENS', 'Wonder', '', 'SCIENCE', 2),	('BUILDING_HANGING_GARDENS', 'Wonder', '', 'CULTURE', 1),	('BUILDING_HANGING_GARDENS', 'Wonder', '', 'RELIGION', 2),	('BUILDING_HANGING_GARDENS', 'Wonder', '', 'CONQUEST', 2),
	('BUILDING_HERMITAGE', 'Wonder', '', 'CULTURE', 8),		
('BUILDING_HUEY_TEOCALLI', 'Wonder', '', 'SCIENCE', 2),	('BUILDING_HUEY_TEOCALLI', 'Wonder', '', 'CULTURE', 1),	('BUILDING_HUEY_TEOCALLI', 'Wonder', '', 'RELIGION', 1),	('BUILDING_HUEY_TEOCALLI', 'Wonder', '', 'CONQUEST', 2),
		('BUILDING_JEBEL_BARKAL', 'Wonder', '', 'RELIGION', 4),	('BUILDING_JEBEL_BARKAL', 'Wonder', '', 'CONQUEST', 3),
('BUILDING_KILWA_KISIWANI', 'Wonder', '', 'SCIENCE', 4),	('BUILDING_KILWA_KISIWANI', 'Wonder', '', 'CULTURE', 4),	('BUILDING_KILWA_KISIWANI', 'Wonder', '', 'RELIGION', 4),	('BUILDING_KILWA_KISIWANI', 'Wonder', '', 'CONQUEST', 4),
		('BUILDING_KOTOKU_IN', 'Wonder', '', 'RELIGION', 3),	('BUILDING_KOTOKU_IN', 'Wonder', '', 'CONQUEST', 6),
		('BUILDING_MAHABODHI_TEMPLE', 'Wonder', '', 'RELIGION', 5),	
	('BUILDING_MONT_ST_MICHEL', 'Wonder', '', 'CULTURE', 5),	('BUILDING_MONT_ST_MICHEL', 'Wonder', '', 'RELIGION', 4),	
('BUILDING_ORACLE', 'Wonder', '', 'SCIENCE', 3),	('BUILDING_ORACLE', 'Wonder', '', 'CULTURE', 4),		
('BUILDING_OXFORD_UNIVERSITY', 'Wonder', '', 'SCIENCE', 6),	('BUILDING_OXFORD_UNIVERSITY', 'Wonder', '', 'CULTURE', 2),		
('BUILDING_PETRA', 'Wonder', '', 'SCIENCE', 2),	('BUILDING_PETRA', 'Wonder', '', 'CULTURE', 2),	('BUILDING_PETRA', 'Wonder', '', 'RELIGION', 2),	('BUILDING_PETRA', 'Wonder', '', 'CONQUEST', 2),
	('BUILDING_POTALA_PALACE', 'Wonder', '', 'CULTURE', 2),	('BUILDING_POTALA_PALACE', 'Wonder', '', 'RELIGION', 2),	
('BUILDING_PYRAMIDS', 'Wonder', '', 'SCIENCE', 2),	('BUILDING_PYRAMIDS', 'Wonder', '', 'CULTURE', 2),	('BUILDING_PYRAMIDS', 'Wonder', '', 'RELIGION', 2),	('BUILDING_PYRAMIDS', 'Wonder', '', 'CONQUEST', 2),
('BUILDING_RUHR_VALLEY', 'Wonder', '', 'SCIENCE', 6),	('BUILDING_RUHR_VALLEY', 'Wonder', '', 'CULTURE', 2),	('BUILDING_RUHR_VALLEY', 'Wonder', '', 'RELIGION', 2),	('BUILDING_RUHR_VALLEY', 'Wonder', '', 'CONQUEST', 5),
			('BUILDING_STATUE_LIBERTY', 'Wonder', '', 'CONQUEST', 5),
		('BUILDING_STONEHENGE', 'Wonder', '', 'RELIGION', 7),	
('BUILDING_ST_BASILS_CATHEDRAL', 'Wonder', '', 'SCIENCE', 1),	('BUILDING_ST_BASILS_CATHEDRAL', 'Wonder', '', 'CULTURE', 7),		
	('BUILDING_SYDNEY_OPERA_HOUSE', 'Wonder', '', 'CULTURE', 8),		
('BUILDING_TAJ_MAHAL', 'Wonder', '', 'SCIENCE', 2),	('BUILDING_TAJ_MAHAL', 'Wonder', '', 'CULTURE', 2),	('BUILDING_TAJ_MAHAL', 'Wonder', '', 'RELIGION', 2),	('BUILDING_TAJ_MAHAL', 'Wonder', '', 'CONQUEST', 2),
('BUILDING_TEMPLE_ARTEMIS', 'Wonder', '', 'SCIENCE', 1),	('BUILDING_TEMPLE_ARTEMIS', 'Wonder', '', 'CULTURE', 1),	('BUILDING_TEMPLE_ARTEMIS', 'Wonder', '', 'RELIGION', 1),	('BUILDING_TEMPLE_ARTEMIS', 'Wonder', '', 'CONQUEST', 1),
	('BUILDING_TERRACOTTA_ARMY', 'Wonder', '', 'CULTURE', 5),		('BUILDING_TERRACOTTA_ARMY', 'Wonder', '', 'CONQUEST', 7),
			('BUILDING_VENETIAN_ARSENAL', 'Wonder', '', 'CONQUEST', 7);
