-- ===========================================================================
-- Real Strategy
-- Author: Infixo
-- 2018-12-14: Created
-- ===========================================================================

-- just to make versioning easier
INSERT INTO GlobalParameters (Name, Value) VALUES ('RST_VERSION_MAJOR', '0');
INSERT INTO GlobalParameters (Name, Value) VALUES ('RST_VERSION_MINOR', '1');

-- Parameters
INSERT INTO GlobalParameters (Name, Value) VALUES
('RST_WEIGHT_POLICY', 2), -- how much each slotted policy weights
('RST_WEIGHT_WONDER', 3), -- how much each wonder weights
('RST_WEIGHT_GOVERNMENT', 5), -- how much each government weights
('RST_STRATEGY_NUM_TURNS_MUST_BE_ACTIVE', 5), -- how many turns a strategy must be active before checking for new priorities, def. 10
('RST_STRATEGY_MINIMUM_PRIORITY', 50), -- minimum priority to activate a strategy
('RST_STRATEGY_CURRENT_PRIORITY', 50), -- how much current strategy adds to the priority
('RST_STRATEGY_RANDOM_PRIORITY', 30), -- random part of the priority, def. 50
('RST_STRATEGY_BETTER_THAN_US_NERF', 33), -- each player better than us decreases out priority by this percent
('RST_CONQUEST_NOBODY_MET_NUM_TURNS', 20), -- will check if anybody met after this many turns, def. 20
('RST_CONQUEST_NOBODY_MET_PRIORITY', -100); -- if nobody met, then decrease the priority, def. -100

/*
INSERT INTO Types (Type, Kind) VALUES
('STRATEGY_TEST_TURN_3', 'KIND_VICTORY_STRATEGY'),
('STRATEGY_TEST_TURN_5', 'KIND_VICTORY_STRATEGY'),
('STRATEGY_TEST_TURN_7', 'KIND_VICTORY_STRATEGY');

INSERT INTO Strategies (StrategyType, VictoryType, NumConditionsNeeded) VALUES
('STRATEGY_TEST_TURN_3', NULL, 1),
('STRATEGY_TEST_TURN_5', NULL, 1),
('STRATEGY_TEST_TURN_7', NULL, 1);
 */

--INSERT INTO StrategyConditions (StrategyType, ConditionFunction, StringValue, ThresholdValue) VALUES
--('STRATTEST_TURN_3','Call Lua Function','CheckTurnNumber',3),
--('STRATTEST_TURN_5','Call Lua Function','CheckTurnNumber',5),
--('STRATTEST_TURN_7','Call Lua Function','CheckTurnNumber',7);


--Good Culture City
--Good Faith City
--Good Tech City

INSERT INTO StrategyConditions (StrategyType, ConditionFunction, ThresholdValue) VALUES
('STRATTEST_Has_Tech_Lead_15', 'Has Tech Lead', 15),
('STRATTEST_Has_Tech_Lead_25', 'Has Tech Lead', 25),
('STRATTEST_Has_Tech_Lead_50', 'Has Tech Lead', 50),
('STRATTEST_Leads_Military_15', 'Leads Military', 15),
('STRATTEST_Leads_Military_25', 'Leads Military', 25),
('STRATTEST_Leads_Military_50', 'Leads Military', 50),
('STRATTEST_Leads_Score_15', 'Leads Score', 15), -- 1/8
('STRATTEST_Leads_Score_25', 'Leads Score', 25), -- 2/8
('STRATTEST_Leads_Score_50', 'Leads Score', 50), -- 4/8
--('STRATTEST_Next_Lower_Score_20', 'Next Lower Score', 20),
--('STRATTEST_Next_Lower_Score_40', 'Next Lower Score', 40),
--('STRATTEST_Next_Lower_Score_60', 'Next Lower Score', 60);
('STRATTEST_Is_Classical_0', 'Is Classical', 0),
('STRATTEST_Is_Classical_1', 'Is Classical', 1),
('STRATTEST_Is_Medieval_0', 'Is Medieval', 0),
('STRATTEST_Is_Medieval_1', 'Is Medieval', 1);


INSERT INTO Types (Type, Kind)
SELECT StrategyType, 'KIND_VICTORY_STRATEGY'
FROM StrategyConditions
WHERE StrategyType LIKE 'STRATTEST%';

INSERT INTO Strategies (StrategyType, NumConditionsNeeded)
SELECT StrategyType, 1
FROM StrategyConditions
WHERE StrategyType LIKE 'STRATTEST%';


CREATE TABLE RSTFlavors (
	ObjectType TEXT NOT NULL,
	Type TEXT NOT NULL CHECK (Type IN ('Parameter', 'STRATEGY', 'LEADER', 'POLICY', 'GOVERNMENT', 'Wonder', 'BELIEF', 'CityState')),
	Subtype TEXT,
	Strategy TEXT NOT NULL CHECK (Strategy IN ('CONQUEST', 'SCIENCE', 'CULTURE', 'RELIGION', 'DIPLO', 'DEFENCE', 'NAVAL', 'TRADE')),
	Value INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY (ObjectType, Strategy)
);

INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
('BasePriority', 'Parameter', 'STRATEGY', 'SCIENCE', 20),	('BasePriority', 'Parameter', 'STRATEGY', 'CULTURE', 20),	('BasePriority', 'Parameter', 'STRATEGY', 'RELIGION', 20),	('BasePriority', 'Parameter', 'STRATEGY', 'CONQUEST', 20),
('SCIENCE', 'Parameter', 'STRATEGY', 'SCIENCE', 2),	('SCIENCE', 'Parameter', 'STRATEGY', 'CULTURE', -2),	('SCIENCE', 'Parameter', 'STRATEGY', 'RELIGION', -2),	('SCIENCE', 'Parameter', 'STRATEGY', 'CONQUEST', 1),
('CULTURE', 'Parameter', 'STRATEGY', 'SCIENCE', -2),	('CULTURE', 'Parameter', 'STRATEGY', 'CULTURE', 2),	('CULTURE', 'Parameter', 'STRATEGY', 'RELIGION', -1),	('CULTURE', 'Parameter', 'STRATEGY', 'CONQUEST', -2),
('RELIGION', 'Parameter', 'STRATEGY', 'SCIENCE', -2),	('RELIGION', 'Parameter', 'STRATEGY', 'CULTURE', -1),	('RELIGION', 'Parameter', 'STRATEGY', 'RELIGION', 2),	
('CONQUEST', 'Parameter', 'STRATEGY', 'SCIENCE', 1),	('CONQUEST', 'Parameter', 'STRATEGY', 'CULTURE', -1),	('CONQUEST', 'Parameter', 'STRATEGY', 'RELIGION', -1),	('CONQUEST', 'Parameter', 'STRATEGY', 'CONQUEST', 3),
('DIPLO', 'Parameter', 'STRATEGY', 'CULTURE', 1),		('DIPLO', 'Parameter', 'STRATEGY', 'CONQUEST', -1);

-- LEADERS
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
('LEADER_ALEXANDER', 'LEADER', '', 'SCIENCE', 5),('LEADER_ALEXANDER', 'LEADER', '', 'CULTURE', 4),('LEADER_ALEXANDER', 'LEADER', '', 'RELIGION', 3),('LEADER_ALEXANDER', 'LEADER', '', 'CONQUEST', 8),
('LEADER_AMANITORE', 'LEADER', '', 'SCIENCE', 2),('LEADER_AMANITORE', 'LEADER', '', 'CULTURE', 3),('LEADER_AMANITORE', 'LEADER', '', 'RELIGION', 6),('LEADER_AMANITORE', 'LEADER', '', 'CONQUEST', 5),
('LEADER_BARBAROSSA', 'LEADER', '', 'SCIENCE', 7),('LEADER_BARBAROSSA', 'LEADER', '', 'CULTURE', 4),('LEADER_BARBAROSSA', 'LEADER', '', 'RELIGION', 4),('LEADER_BARBAROSSA', 'LEADER', '', 'CONQUEST', 6),
('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'SCIENCE', 6),('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'CULTURE', 8),('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'RELIGION', 4),('LEADER_CATHERINE_DE_MEDICI', 'LEADER', '', 'CONQUEST', 4),
('LEADER_CHANDRAGUPTA', 'LEADER', '', 'SCIENCE', 4),('LEADER_CHANDRAGUPTA', 'LEADER', '', 'CULTURE', 4),('LEADER_CHANDRAGUPTA', 'LEADER', '', 'RELIGION', 5),('LEADER_CHANDRAGUPTA', 'LEADER', '', 'CONQUEST', 6),
('LEADER_CLEOPATRA', 'LEADER', '', 'SCIENCE', 5),('LEADER_CLEOPATRA', 'LEADER', '', 'CULTURE', 6),('LEADER_CLEOPATRA', 'LEADER', '', 'RELIGION', 5),('LEADER_CLEOPATRA', 'LEADER', '', 'CONQUEST', 5),
('LEADER_CYRUS', 'LEADER', '', 'SCIENCE', 5),('LEADER_CYRUS', 'LEADER', '', 'CULTURE', 4),('LEADER_CYRUS', 'LEADER', '', 'RELIGION', 4),('LEADER_CYRUS', 'LEADER', '', 'CONQUEST', 8),
('LEADER_GANDHI', 'LEADER', '', 'SCIENCE', 5),('LEADER_GANDHI', 'LEADER', '', 'CULTURE', 7),('LEADER_GANDHI', 'LEADER', '', 'RELIGION', 8),('LEADER_GANDHI', 'LEADER', '', 'CONQUEST', 2),
('LEADER_GENGHIS_KHAN', 'LEADER', '', 'SCIENCE', 4),('LEADER_GENGHIS_KHAN', 'LEADER', '', 'CULTURE', 2),('LEADER_GENGHIS_KHAN', 'LEADER', '', 'RELIGION', 2),('LEADER_GENGHIS_KHAN', 'LEADER', '', 'CONQUEST', 8),
('LEADER_GILGAMESH', 'LEADER', '', 'SCIENCE', 8),('LEADER_GILGAMESH', 'LEADER', '', 'CULTURE', 4),('LEADER_GILGAMESH', 'LEADER', '', 'RELIGION', 2),('LEADER_GILGAMESH', 'LEADER', '', 'CONQUEST', 5),
('LEADER_GITARJA', 'LEADER', '', 'SCIENCE', 4),('LEADER_GITARJA', 'LEADER', '', 'CULTURE', 5),('LEADER_GITARJA', 'LEADER', '', 'RELIGION', 7),('LEADER_GITARJA', 'LEADER', '', 'CONQUEST', 3),
('LEADER_GORGO', 'LEADER', '', 'SCIENCE', 2),('LEADER_GORGO', 'LEADER', '', 'CULTURE', 5),('LEADER_GORGO', 'LEADER', '', 'RELIGION', 3),('LEADER_GORGO', 'LEADER', '', 'CONQUEST', 7),
('LEADER_HARDRADA', 'LEADER', '', 'SCIENCE', 5),('LEADER_HARDRADA', 'LEADER', '', 'CULTURE', 1),('LEADER_HARDRADA', 'LEADER', '', 'RELIGION', 5),('LEADER_HARDRADA', 'LEADER', '', 'CONQUEST', 7),
('LEADER_HOJO', 'LEADER', '', 'SCIENCE', 5),('LEADER_HOJO', 'LEADER', '', 'CULTURE', 4),('LEADER_HOJO', 'LEADER', '', 'RELIGION', 2),('LEADER_HOJO', 'LEADER', '', 'CONQUEST', 7),
('LEADER_JADWIGA', 'LEADER', '', 'SCIENCE', 4),('LEADER_JADWIGA', 'LEADER', '', 'CULTURE', 6),('LEADER_JADWIGA', 'LEADER', '', 'RELIGION', 7),('LEADER_JADWIGA', 'LEADER', '', 'CONQUEST', 4),
('LEADER_JAYAVARMAN', 'LEADER', '', 'SCIENCE', 4),('LEADER_JAYAVARMAN', 'LEADER', '', 'CULTURE', 5),('LEADER_JAYAVARMAN', 'LEADER', '', 'RELIGION', 8),('LEADER_JAYAVARMAN', 'LEADER', '', 'CONQUEST', 3),
('LEADER_JOHN_CURTIN', 'LEADER', '', 'SCIENCE', 6),('LEADER_JOHN_CURTIN', 'LEADER', '', 'CULTURE', 6),('LEADER_JOHN_CURTIN', 'LEADER', '', 'RELIGION', 4),('LEADER_JOHN_CURTIN', 'LEADER', '', 'CONQUEST', 4),
('LEADER_LAUTARO', 'LEADER', '', 'SCIENCE', 2),('LEADER_LAUTARO', 'LEADER', '', 'CULTURE', 7),('LEADER_LAUTARO', 'LEADER', '', 'RELIGION', 3),('LEADER_LAUTARO', 'LEADER', '', 'CONQUEST', 7),
('LEADER_MONTEZUMA', 'LEADER', '', 'SCIENCE', 3),('LEADER_MONTEZUMA', 'LEADER', '', 'CULTURE', 2),('LEADER_MONTEZUMA', 'LEADER', '', 'RELIGION', 2),('LEADER_MONTEZUMA', 'LEADER', '', 'CONQUEST', 9),
('LEADER_MVEMBA', 'LEADER', '', 'SCIENCE', 6),('LEADER_MVEMBA', 'LEADER', '', 'CULTURE', 8),('LEADER_MVEMBA', 'LEADER', '', 'RELIGION', 1),('LEADER_MVEMBA', 'LEADER', '', 'CONQUEST', 2),
('LEADER_PEDRO', 'LEADER', '', 'SCIENCE', 6),('LEADER_PEDRO', 'LEADER', '', 'CULTURE', 8),('LEADER_PEDRO', 'LEADER', '', 'RELIGION', 3),('LEADER_PEDRO', 'LEADER', '', 'CONQUEST', 3),
('LEADER_PERICLES', 'LEADER', '', 'SCIENCE', 5),('LEADER_PERICLES', 'LEADER', '', 'CULTURE', 8),('LEADER_PERICLES', 'LEADER', '', 'RELIGION', 3),('LEADER_PERICLES', 'LEADER', '', 'CONQUEST', 3),
('LEADER_PETER_GREAT', 'LEADER', '', 'SCIENCE', 5),('LEADER_PETER_GREAT', 'LEADER', '', 'CULTURE', 5),('LEADER_PETER_GREAT', 'LEADER', '', 'RELIGION', 6),('LEADER_PETER_GREAT', 'LEADER', '', 'CONQUEST', 4),
('LEADER_PHILIP_II', 'LEADER', '', 'SCIENCE', 4),('LEADER_PHILIP_II', 'LEADER', '', 'CULTURE', 3),('LEADER_PHILIP_II', 'LEADER', '', 'RELIGION', 7),('LEADER_PHILIP_II', 'LEADER', '', 'CONQUEST', 5),
('LEADER_POUNDMAKER', 'LEADER', '', 'SCIENCE', 6),('LEADER_POUNDMAKER', 'LEADER', '', 'CULTURE', 5),('LEADER_POUNDMAKER', 'LEADER', '', 'RELIGION', 5),('LEADER_POUNDMAKER', 'LEADER', '', 'CONQUEST', 4),
('LEADER_QIN', 'LEADER', '', 'SCIENCE', 6),('LEADER_QIN', 'LEADER', '', 'CULTURE', 7),('LEADER_QIN', 'LEADER', '', 'RELIGION', 5),('LEADER_QIN', 'LEADER', '', 'CONQUEST', 5),
('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'SCIENCE', 7),('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'CULTURE', 4),('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'RELIGION', 2),('LEADER_ROBERT_THE_BRUCE', 'LEADER', '', 'CONQUEST', 4),
('LEADER_SALADIN', 'LEADER', '', 'SCIENCE', 7),('LEADER_SALADIN', 'LEADER', '', 'CULTURE', 4),('LEADER_SALADIN', 'LEADER', '', 'RELIGION', 7),('LEADER_SALADIN', 'LEADER', '', 'CONQUEST', 4),
('LEADER_SEONDEOK', 'LEADER', '', 'SCIENCE', 9),('LEADER_SEONDEOK', 'LEADER', '', 'CULTURE', 5),('LEADER_SEONDEOK', 'LEADER', '', 'RELIGION', 1),('LEADER_SEONDEOK', 'LEADER', '', 'CONQUEST', 5),
('LEADER_SHAKA', 'LEADER', '', 'SCIENCE', 3),('LEADER_SHAKA', 'LEADER', '', 'CULTURE', 2),('LEADER_SHAKA', 'LEADER', '', 'RELIGION', 2),('LEADER_SHAKA', 'LEADER', '', 'CONQUEST', 9),
('LEADER_TAMAR', 'LEADER', '', 'SCIENCE', 3),('LEADER_TAMAR', 'LEADER', '', 'CULTURE', 4),('LEADER_TAMAR', 'LEADER', '', 'RELIGION', 7),('LEADER_TAMAR', 'LEADER', '', 'CONQUEST', 6),
('LEADER_TOMYRIS', 'LEADER', '', 'SCIENCE', 2),('LEADER_TOMYRIS', 'LEADER', '', 'CULTURE', 3),('LEADER_TOMYRIS', 'LEADER', '', 'RELIGION', 4),('LEADER_TOMYRIS', 'LEADER', '', 'CONQUEST', 8),
('LEADER_TRAJAN', 'LEADER', '', 'SCIENCE', 4),('LEADER_TRAJAN', 'LEADER', '', 'CULTURE', 2),('LEADER_TRAJAN', 'LEADER', '', 'RELIGION', 2),('LEADER_TRAJAN', 'LEADER', '', 'CONQUEST', 8),
('LEADER_T_ROOSEVELT', 'LEADER', '', 'SCIENCE', 5),('LEADER_T_ROOSEVELT', 'LEADER', '', 'CULTURE', 7),('LEADER_T_ROOSEVELT', 'LEADER', '', 'RELIGION', 3),('LEADER_T_ROOSEVELT', 'LEADER', '', 'CONQUEST', 4),
('LEADER_VICTORIA', 'LEADER', '', 'SCIENCE', 5),('LEADER_VICTORIA', 'LEADER', '', 'CULTURE', 7),('LEADER_VICTORIA', 'LEADER', '', 'RELIGION', 2),('LEADER_VICTORIA', 'LEADER', '', 'CONQUEST', 7),
('LEADER_WILHELMINA', 'LEADER', '', 'SCIENCE', 5),('LEADER_WILHELMINA', 'LEADER', '', 'CULTURE', 6),('LEADER_WILHELMINA', 'LEADER', '', 'RELIGION', 2),('LEADER_WILHELMINA', 'LEADER', '', 'CONQUEST', 5);

-- GOVERNMENTS
INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'SCIENCE', 2),('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'CULTURE', 2),('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'RELIGION', 2),('GOVERNMENT_CHIEFDOM', 'GOVERNMENT', 'TIER_0', 'CONQUEST', 2),
('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'SCIENCE', 2),('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'CULTURE', 4),('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'RELIGION', 2),('GOVERNMENT_AUTOCRACY', 'GOVERNMENT', 'TIER_1', 'CONQUEST', 4),
('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'SCIENCE', 2),('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'CULTURE', 2),('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'RELIGION', 2),('GOVERNMENT_OLIGARCHY', 'GOVERNMENT', 'TIER_1', 'CONQUEST', 5),
('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'SCIENCE', 3),('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'CULTURE', 3),('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'RELIGION', 2),('GOVERNMENT_CLASSICAL_REPUBLIC', 'GOVERNMENT', 'TIER_1', 'CONQUEST', 2),
('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'SCIENCE', 3),('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'CULTURE', 3),('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'RELIGION', 4),('GOVERNMENT_MONARCHY', 'GOVERNMENT', 'TIER_2', 'CONQUEST', 5),
('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'SCIENCE', 3),('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'CULTURE', 3),('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'RELIGION', 6),('GOVERNMENT_THEOCRACY', 'GOVERNMENT', 'TIER_2', 'CONQUEST', 4),
('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'SCIENCE', 5),('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'CULTURE', 5),('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'RELIGION', 3),('GOVERNMENT_MERCHANT_REPUBLIC', 'GOVERNMENT', 'TIER_2', 'CONQUEST', 3),
('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'SCIENCE', 3),('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'CULTURE', 3),('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'RELIGION', 1),('GOVERNMENT_FASCISM', 'GOVERNMENT', 'TIER_3', 'CONQUEST', 9),
('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'SCIENCE', 8),('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'CULTURE', 4),('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'RELIGION', 1),('GOVERNMENT_COMMUNISM', 'GOVERNMENT', 'TIER_3', 'CONQUEST', 4),
('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'SCIENCE', 5),('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'CULTURE', 8),('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'RELIGION', 4),('GOVERNMENT_DEMOCRACY', 'GOVERNMENT', 'TIER_3', 'CONQUEST', 1);

INSERT INTO RSTFlavors (ObjectType, Type, Subtype, Strategy, Value) VALUES -- generated from Excel
-- POLICIES
('POLICY_DISCIPLINE', 'POLICY', 'MILITARY', 'CONQUEST', 1),
('POLICY_URBAN_PLANNING', 'POLICY', 'ECONOMIC', 'CONQUEST', 3),
('POLICY_URBAN_PLANNING', 'POLICY', 'MILITARY', 'SCIENCE', 3),
('POLICY_URBAN_PLANNING', 'POLICY', 'MILITARY', 'CULTURE', 3),
('POLICY_DIPLOMATIC_LEAGUE', 'POLICY', 'DIPLOMATIC', 'DIPLO', 3),
('POLICY_GOD_KING', 'POLICY', 'ECONOMIC', 'RELIGION', 5),
('POLICY_AESTHETICS', 'POLICY', 'ECONOMIC', 'CULTURE', 8),
('POLICY_AGOGE', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_CHIVALRY', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_COLLECTIVE_ACTIVISM', 'POLICY', 'DIPLOMATIC', 'CULTURE', 5),
('POLICY_CRYPTOGRAPHY', 'POLICY', 'DIPLOMATIC', 'CONQUEST', 1),
('POLICY_FEUDAL_CONTRACT', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_FINEST_HOUR', 'POLICY', 'MILITARY', 'CONQUEST', 7),
('POLICY_FRESCOES', 'POLICY', 'GREAT_PERSON', 'CULTURE', 5),
('POLICY_GRANDE_ARMEE', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_GUNBOAT_DIPLOMACY', 'POLICY', 'DIPLOMATIC', 'SCIENCE', 5),
('POLICY_INSPIRATION', 'POLICY', 'GREAT_PERSON', 'SCIENCE', 5),
('POLICY_INTEGRATED_SPACE_CELL', 'POLICY', 'MILITARY', 'SCIENCE', 7),
('POLICY_INTERNATIONAL_WATERS', 'POLICY', 'MILITARY', 'CONQUEST', 3),
('POLICY_INVENTION', 'POLICY', 'GREAT_PERSON', 'SCIENCE', 2),('POLICY_INVENTION', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 2),






('POLICY_LIGHTNING_WARFARE', 'POLICY', 'MILITARY', 'CONQUEST', 7),


('POLICY_LITERARY_TRADITION', 'POLICY', 'GREAT_PERSON', 'CULTURE', 5),
('POLICY_LOGISTICS', 'POLICY', 'MILITARY', 'CONQUEST', 5),

('POLICY_MANEUVER', 'POLICY', 'MILITARY', 'CONQUEST', 7),
('POLICY_MARITIME_INDUSTRIES', 'POLICY', 'MILITARY', 'CONQUEST', 3),

('POLICY_MARTIAL_LAW', 'POLICY', 'MILITARY', 'CONQUEST', 7),



('POLICY_MILITARY_FIRST', 'POLICY', 'MILITARY', 'CONQUEST', 6),
('POLICY_MILITARY_ORGANIZATION', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 8),
('POLICY_MILITARY_RESEARCH', 'POLICY', 'MILITARY', 'SCIENCE', 3),

('POLICY_NATIONAL_IDENTITY', 'POLICY', 'MILITARY', 'CONQUEST', 7),
('POLICY_NATIVE_CONQUEST', 'POLICY', 'MILITARY', 'CONQUEST', 5),


('POLICY_NAVIGATION', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 3),

('POLICY_NOBEL_PRIZE', 'POLICY', 'GREAT_PERSON', 'SCIENCE', 5),


('POLICY_PATRIOTIC_WAR', 'POLICY', 'MILITARY', 'CONQUEST', 3),


('POLICY_PRESS_GANGS', 'POLICY', 'MILITARY', 'CONQUEST', 4),
('POLICY_PROFESSIONAL_ARMY', 'POLICY', 'MILITARY', 'CONQUEST', 5),
('POLICY_PROPAGANDA', 'POLICY', 'MILITARY', 'CONQUEST', 7),


('POLICY_RAID', 'POLICY', 'MILITARY', 'SCIENCE', 2),('POLICY_RAID', 'POLICY', 'MILITARY', 'CULTURE', 2),('POLICY_RAID', 'POLICY', 'MILITARY', 'RELIGION', 2),('POLICY_RAID', 'POLICY', 'MILITARY', 'CONQUEST', 5),
('POLICY_RAJ', 'POLICY', 'DIPLOMATIC', 'SCIENCE', 2),('POLICY_RAJ', 'POLICY', 'DIPLOMATIC', 'CULTURE', 2),('POLICY_RAJ', 'POLICY', 'DIPLOMATIC', 'RELIGION', 2),




('POLICY_REVELATION', 'POLICY', 'GREAT_PERSON', 'RELIGION', 8),

('POLICY_ROGUE_STATE', 'POLICY', 'WILDCARD', 'SCIENCE', 2),('POLICY_ROGUE_STATE', 'POLICY', 'WILDCARD', 'CULTURE', 2),('POLICY_ROGUE_STATE', 'POLICY', 'WILDCARD', 'RELIGION', 2),('POLICY_ROGUE_STATE', 'POLICY', 'WILDCARD', 'CONQUEST', 5),







('POLICY_STRATEGIC_AIR_FORCE', 'POLICY', 'MILITARY', 'CONQUEST', 5),
('POLICY_STRATEGOS', 'POLICY', 'GREAT_PERSON', 'CONQUEST', 5),

('POLICY_SYMPHONIES', 'POLICY', 'GREAT_PERSON', 'CULTURE', 6),

('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'SCIENCE', 2),('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'CULTURE', 2),('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'RELIGION', 2),('POLICY_TOTAL_WAR', 'POLICY', 'MILITARY', 'CONQUEST', 5),






('POLICY_VETERANCY', 'POLICY', 'MILITARY', 'CONQUEST', 4),
('POLICY_WARS_OF_RELIGION', 'POLICY', 'MILITARY', 'CONQUEST', 6);

